package moe.sekiu.minilpa.model

import kotlinx.serialization.Serializable

@Serializable
data class Language @JvmOverloads constructor(
    val `language-name` : String = "English (US)",
    val profile : String = "Profile",
    val notification : String = "Notification",
    val chip : String = "Chip",
    val setting : String = "Setting",
    val `free-space` : String = "Free Space: %s",
    val download : String = "Download",
    val install : String = "Install",
    val delete : String = "Delete",
    val enable : String = "Enable",
    val disable : String = "Disable",
    val `edit-nickname` : String = "Edit Nickname",
    val `device-selector` : String = "Device Selector",
    val `refresh-devices` : String = "Refresh Devices",
    val `refresh-card` : String = "Refresh Card",
    val `show-details` : String = "Show Details",
    val `match-case` : String = "Match Case",
    val `whole-words` : String = "Whole Words",
    val `regular-expression` : String = "Regular Expression",
    val `to-notification` : String = "To Notification",
    val `to-profile` : String = "To Profile",
    val search : String = "Search",
    val process : String = "Process",
    val remove : String = "Remove",
    val `select-all` : String = "Select All",
    val `cancel-selection` : String = "Cancel Selection",
    val `batch-select` : String = "Batch Select",
    val selected : String = "Selected: %s",
    val edit : String = "Edit",
    val copy : String = "Copy",
    val `copy-key` : String = "Copy Key",
    val `copy-value` : String = "Copy Value",
    val `copy-key-and-value` : String = "Copy Key and Value",

    val `download-profile-title` : String = "Download Profile",
    val `SMDP+` : String = "SM-DP+",
    val `matching-id` : String = "Matching Id",
    val `confirmation-code-required` : String = "Confirmation Code Required",
    val `confirmation-code` : String = "Confirmation Code",
    val `specified-IMEI` : String = "Specified IMEI",
    val IMEI : String = "IMEI",
    val `process-install-notification` : String = "Process Install Notification",
    val `process-delete-notification` : String = "Process Delete Notification",
    val `process-enable-notification` : String = "Process Enable Notification",
    val `process-disable-notification` : String = "Process Disable Notification",
    val `and-remove` : String = "and Remove",

    val `edit-nickname-message` : String = "Please enter a new nickname",
    val `notification-remove-message` : String = "Are you sure you want to remove these notification?",
    val `profile-delete-message` : String = "Are you sure you want to delete this profile?",
    val `operation-success-title` : String = "Operation Success",
    val `operation-success-profile-download` : String = "Profile download success",
    val `operation-success-profile-delete` : String = "Profile delete success",
    val `operation-success-notification-process` : String = "Notification process success",
    val `operation-success-notification-remove` : String = "Notification remove success",
    val `operation-failed-title` : String = "Operation Failed",
    val `operation-failed-error` : String = "We have encountered an error",
    val `operation-failed-stage` : String = "Stage: %s",
    val `operation-failed-info` : String = "Info: %s",
    val `operation-failed-type` : String = "Type: %s",
    val `operation-failed-check-the-log` : String = "Check the log for more information.",
    val `operation-failed-select-device` : String = "Please select a device.",

    val `empty-tag` : String = "<Empty>",
    val `not-set-tag` : String = "<Not Set>",
    val `deleted-tag` : String = "<Deleted>",

    val eid : String = "Eid",
    val `default-SMDP+-address` : String = "Default SM-DP+ Address",
    val `root-smds-address` : String = "Root SM-DS Address",
    val `edit-default-SMDP+-address` : String = "Edit Default SMDP+ Address",
    val `edit-default-SMDP+-address-message` : String = "Please enter a new Default SMDP+ Address",
    val manufacturer : String = "Manufacturer:",
    val unknown : String = "Unknown",
    val `secure-element` : String = "Secure Element: %s",
    val `certificate-issuers` : String = "Certificate Issuers",
    val `open-external-link` : String = "Open External Link",

    val processing : String = "Processing",
    val initializing : String = "Initializing",
    val complete : String = "Complete",
    val `profile-get-list` : String = "Get Profile List",
    val `profile-enable` : String = "Enable Profile",
    val `profile-disable` : String = "Disable Profile",
    val `profile-download` : String = "Download Profile",
    val `profile-delete` : String = "Delete Profile",
    val `profile-edit-nickname` : String = "Edit Profile Nickname",
    val `notification-get-list` : String = "Get Notification List",
    val `notification-remove` : String = "Remove Notification",
    val `notification-process` : String = "Process Notification",
    val `get-chip-info` : String = "Get Chip Info",

    val `lpac-not-found-or-invalid` : String = "lpac executable not found or is invalid.\nPlease put lpac in %s",
    val `lpac-output-not-captured` : String = "lpac output not captured",

    val `profile-drop-here` : String = "Drop Activation Code or QR Code here",
    val `download-drop-here` : String = "Drop Activation Code\nor QR Code here",
    val `to-auto-parse` : String = "to auto parse",
    val `ac-parseing-failed` : String = "Activation code parsing failed.",

    val about : String = "About",
    val `runtime-version` : String = "Runtime Version: %s",
    val VM : String = "VM: %s",
    val language : String = "Language",
    val `open-language-folder` : String = "Open Language Folder",
    val log : String = "Log",
    val `open-latest-log` : String = "Open Latest Log",
    val `open-log-floder` : String = "Open Log Folder",
    val backend : String = "Backend",
    val `lpac-version` : String = "lpac Version: %s",
    val `open-lpac-folder` : String = "Open lpac Folder",
    val `libeuicc-apdu-debug` : String = "LibEuicc APDU Debug",
    val `libeuicc-http-debug` : String = "LibEuicc HTTP Debug",
    val behavior : String = "Behavior",
    val appearance : String = "Appearance",
    val `emoji-design` : String = "Emoji Design",
    val `auto-night-mode` : String = "Auto-Night Mode",
    val system : String = "System",
    val disabled : String = "Disabled",
    val `daytime-theme` : String = "Daytime Theme",
    val `nighttime-theme` : String = "Nighttime Theme",
    val `core-themes` : String = "Core Themes",
    val `material-ui-lite-themes` : String = "Material UI Lite Themes",
    val `collection-themes` : String = "Collection Themes",
    val `native-themes` : String = "Native Themes"
)